FROM ruby:4.0.0

RUN apt-get update -qq && apt-get install -y build-essential libvips mariadb-client pkg-config

WORKDIR /lobsters

COPY Gemfile Gemfile.lock .ruby-version ./
RUN bundle config set --local without 'development test' &&     bundle install

COPY . .
RUN mkdir -p log tmp

ENV RAILS_ENV=production
ENV SECRET_KEY_BASE=dummy_key_for_assets
RUN bundle exec rails assets:precompile

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
